#!/bin/bash
# #######################################################################################
# WALLPAPER CHANGER + AUTO-THEMING
# Usage:
#   wallpaper.sh                  → open rofi picker to select from ~/Pictures/Wallpapers
#   wallpaper.sh /path/to/img     → set a specific wallpaper directly
#
# Requires: swww, python-pywal, waybar, rofi, jq
# #######################################################################################

WALLS_DIR="${WALLS_DIR:-$HOME/Pictures/Wallpapers}"
WAL_CACHE="$HOME/.cache/wal"
WAYBAR_COLORS="$HOME/.config/waybar/pywal-colors.css"
ALACRITTY_COLORS="$HOME/.config/alacritty/themes/pywal.toml"

# ── Helper ────────────────────────────────────────────────────────────────────
die() { echo "[wallpaper] ERROR: $*" >&2; exit 1; }

# ── Ensure swww daemon is running ─────────────────────────────────────────────
if ! pgrep -x swww-daemon &>/dev/null; then
    swww-daemon &
    sleep 0.5
fi

# ── Pick wallpaper ────────────────────────────────────────────────────────────
if [[ -n "$1" && -f "$1" ]]; then
    WALLPAPER="$1"
else
    # Rofi picker — list all images in Wallpapers dir
    mkdir -p "$WALLS_DIR"
    WALLPAPER=$(find "$WALLS_DIR" -type f \( \
        -iname "*.jpg" -o -iname "*.jpeg" -o \
        -iname "*.png" -o -iname "*.webp" -o \
        -iname "*.gif" \) | sort | \
        rofi -dmenu -i \
             -p "  Wallpaper" \
             -format 'p' \
             -theme-str 'window {width: 700px;} listview {lines: 10;}')

    [[ -z "$WALLPAPER" ]] && exit 0
fi

[[ -f "$WALLPAPER" ]] || die "File not found: $WALLPAPER"

echo "[wallpaper] Setting: $WALLPAPER"

# ── Apply wallpaper via swww (smooth animated transition) ─────────────────────
swww img "$WALLPAPER" \
    --transition-type grow \
    --transition-pos center \
    --transition-duration 1.2 \
    --transition-fps 60 \
    --transition-bezier .43,1.19,1,.4

# ── Generate color scheme with pywal ─────────────────────────────────────────
echo "[wallpaper] Generating color scheme with pywal..."
wal -i "$WALLPAPER" -n -q --backend wal

# ── Source the generated colors ───────────────────────────────────────────────
source "$WAL_CACHE/colors.sh"

# ── Write Waybar CSS Variables ────────────────────────────────────────────────
echo "[wallpaper] Writing waybar colors..."
cat > "$WAYBAR_COLORS" << WALCSS
/* pywal generated — $(date '+%Y-%m-%d %H:%M:%S') */
/* Source wallpaper: $(basename "$WALLPAPER") */
* {
    --wal-bg:     ${background};
    --wal-fg:     ${foreground};
    --wal-color0: ${color0};
    --wal-color1: ${color1};
    --wal-color2: ${color2};
    --wal-color3: ${color3};
    --wal-color4: ${color4};
    --wal-color5: ${color5};
    --wal-color6: ${color6};
    --wal-color7: ${color7};
    --wal-accent: ${color4};
}
WALCSS

# ── Write Alacritty toml colors ───────────────────────────────────────────────
echo "[wallpaper] Writing alacritty colors..."
cat > "$ALACRITTY_COLORS" << ALAC
# pywal generated — $(date '+%Y-%m-%d %H:%M:%S')
[colors.primary]
  background = "${background}"
  foreground = "${foreground}"

[colors.cursor]
  text   = "${background}"
  cursor = "${foreground}"

[colors.normal]
  black   = "${color0}"
  red     = "${color1}"
  green   = "${color2}"
  yellow  = "${color3}"
  blue    = "${color4}"
  magenta = "${color5}"
  cyan    = "${color6}"
  white   = "${color7}"

[colors.bright]
  black   = "${color8}"
  red     = "${color9}"
  green   = "${color10}"
  yellow  = "${color11}"
  blue    = "${color12}"
  magenta = "${color13}"
  cyan    = "${color14}"
  white   = "${color15}"
ALAC

# ── Write Hyprland border colors ──────────────────────────────────────────────
echo "[wallpaper] Updating Hyprland border color..."
hyprctl keyword general:col.active_border "rgba(${color4/\#/}cc)" 2>/dev/null || true

# ── Reload Waybar ─────────────────────────────────────────────────────────────
echo "[wallpaper] Reloading Waybar..."
pkill -SIGUSR2 waybar 2>/dev/null || (pkill waybar 2>/dev/null; sleep 0.3; waybar &)

# ── Notify ────────────────────────────────────────────────────────────────────
notify-send \
    --app-name="Wallpaper" \
    --icon="preferences-desktop-wallpaper" \
    "Wallpaper Changed" \
    "$(basename "$WALLPAPER")\nTheme auto-generated by pywal" \
    --expire-time=3000 2>/dev/null || true

echo "[wallpaper] Done! 🎨"
